name: ksoc-guard

on: [ push ]

jobs:
    ksoc-guard:
      permissions:
        security-events: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
  @@ -12,4 +14,11 @@ jobs:
          id: guard
          uses: ksoclabs/guard-action@v0.0.10
          with:
            format: sarif
            policy_dir: /policies
        - name: Upload KSOC Guard SARIF Report
          if: success() || failure()
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: ${{ steps.guard.outputs.sarif }}
            checkout_path: /github/workspace